apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: {{ .Values.portainer.image }}
        ports:
        - containerPort: 9000
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
