apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-interface
  template:
    metadata:
      labels:
        app: weather-interface
    spec:
      containers:
      - name: weather-interface
        image: {{ .Values.weatherInterface.image }}
        ports:
        - containerPort: 80
        env:
        - name: ASPNET_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__Marten
          value: "host=postgres; port=5432; database=postgres; username=postgres; password={{ .Values.postgresPassword }}"
